sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t marceli96/docker-react -f Dockerfile.dev  .

script:
    - docker run -e CI=true marceli96/docker-react npm run test